#!/usr/bin/env python3
"""
🪵 30-DAY SNIPER AUDIT: DEC 2025 - JAN 2026 🚀
Comprehensive reconstruction of every trade signal generated by the Trio Ensemble.
Targeting: Winner Hunter, MTF Scalper, and Volume Gem Sniper.
"""
import os
import sys
import pandas as pd
import numpy as np
import xgboost as xgb
import lightgbm as lgb
from catboost import CatBoostClassifier
import requests
from datetime import datetime, timedelta
import warnings
warnings.filterwarnings('ignore')

# Add paths
sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'utils'))
from utils.feature_engineer import add_all_indicators

MODEL_DIR = 'training/models/'

class MonthlyAudit:
    def __init__(self):
        print("📦 Loading Trio Ensemble Models...")
        self.wh_prefix = os.path.join(MODEL_DIR, 'winner_hunter_1h_trio_')
        self.mtf_prefix = os.path.join(MODEL_DIR, 'mtf_scalper_5m_trio_')
        
        self.mtf_xgb = xgb.XGBClassifier(); self.mtf_xgb.load_model(f'{self.mtf_prefix}xgb.json')
        self.mtf_lgb = lgb.Booster(model_file=f'{self.mtf_prefix}lgb.json')
        self.mtf_cat = CatBoostClassifier(); self.mtf_cat.load_model(f'{self.mtf_prefix}cat.json')
        
        self.wh_xgb = xgb.XGBClassifier(); self.wh_xgb.load_model(f'{self.wh_prefix}xgb.json')
        self.wh_lgb = lgb.Booster(model_file=f'{self.wh_prefix}lgb.json')
        self.wh_cat = CatBoostClassifier(); self.wh_cat.load_model(f'{self.wh_prefix}cat.json')

    def fetch_data(self, interval, days=31):
        url = 'https://api.hyperliquid.xyz/info'
        all_data = []
        end_time = int(datetime.now().timestamp() * 1000)
        start_time = int((datetime.now() - timedelta(days=days)).timestamp() * 1000)
        
        current_end = end_time
        print(f"📥 Fetching {days} days of {interval} data in chunks...")
        while current_end > start_time:
            payload = {'type': 'candleSnapshot', 'req': {'coin': 'BTC', 'interval': interval, 'startTime': start_time, 'endTime': current_end}}
            resp = requests.post(url, json=payload, timeout=10)
            if resp.status_code != 200: break
            data = resp.json()
            if not data or not isinstance(data, list): break
            all_data.extend(data)
            current_end = data[0]['t'] - 1
            if len(data) < 500: break
            
        df = pd.DataFrame([[c['t'], float(c['o']), float(c['h']), float(c['l']), float(c['c']), float(c['v'])] for c in all_data], 
                         columns=['timestamp', 'open', 'high', 'low', 'close', 'volume'])
        df['timestamp'] = pd.to_datetime(df['timestamp'], unit='ms')
        df.sort_values('timestamp', inplace=True)
        return df

    def get_probs(self, df_5m, df_15m, df_1h, target='mtf'):
        exclude = ['open', 'high', 'low', 'close', 'volume']
        df_5m_idx = df_5m.set_index('timestamp')
        df_15m_idx = df_15m.set_index('timestamp')
        df_1h_idx = df_1h.set_index('timestamp')
        
        if target == 'wh':
            base_df = df_1h_idx.copy()
            ctx_5m = df_5m_idx[[c for c in df_5m_idx.columns if c not in exclude]].copy()
            ctx_5m.columns = [f"{c}_5m" for c in ctx_5m.columns]
            ctx_15m = df_15m_idx[[c for c in df_15m_idx.columns if c not in exclude]].copy()
            ctx_15m.columns = [f"{c}_15m" for c in ctx_15m.columns]
            df_final = pd.concat([base_df, ctx_5m.reindex(base_df.index, method='ffill'), ctx_15m.reindex(base_df.index, method='ffill')], axis=1).dropna()
            X = np.nan_to_num(df_final[[c for c in df_final.columns if c not in exclude]].values, nan=0.0)
            probs = (self.wh_xgb.predict_proba(X)[:,1] + self.wh_lgb.predict(X) + self.wh_cat.predict_proba(X)[:,1]) / 3
        else:
            base_df = df_5m_idx.copy()
            ctx_1h = df_1h_idx[[c for c in df_1h_idx.columns if c not in exclude]].copy()
            ctx_1h.columns = [f"{c}_1h" for c in ctx_1h.columns]
            ctx_15m = df_15m_idx[[c for c in df_15m_idx.columns if c not in exclude]].copy()
            ctx_15m.columns = [f"{c}_15m" for c in ctx_15m.columns]
            df_final = pd.concat([base_df, ctx_1h.reindex(base_df.index, method='ffill'), ctx_15m.reindex(base_df.index, method='ffill')], axis=1).dropna()
            X = np.nan_to_num(df_final[[c for c in df_final.columns if c not in exclude]].values, nan=0.0)
            probs = (self.mtf_xgb.predict_proba(X)[:,1] + self.mtf_lgb.predict(X) + self.mtf_cat.predict_proba(X)[:,1]) / 3
            
        return df_final, probs

    def simulate(self):
        print("\n" + "🏁"*30)
        print("🪵  30-DAY CONSOLIDATED TRADE LOG AUDIT")
        print("🏁"*30)
        
        df_5m_raw = self.fetch_data('5m')
        df_15m_raw = self.fetch_data('15m')
        df_1h_raw = self.fetch_data('1h')
        
        print("\n🔧 Engineering full month features...")
        df_5m = add_all_indicators(df_5m_raw)
        df_15m = add_all_indicators(df_15m_raw)
        df_1h = add_all_indicators(df_1h_raw)
        
        configs = [
            {'name': 'Winner Hunter (1H)', 'target': 'wh', 'thresh': 0.5248, 'tp': 0.015, 'sl': 0.008},
            {'name': 'MTF Scalper (5M)', 'target': 'mtf', 'thresh': 0.90,   'tp': 0.015, 'sl': 0.008},
            {'name': 'Gem Sniper (5M)',  'target': 'mtf', 'thresh': 0.75,   'tp': 0.003, 'sl': 0.005}
        ]
        
        all_trades = []
        
        for cfg in configs:
            print(f"🔍 Analyzing {cfg['name']}...")
            df, probs = self.get_probs(df_5m, df_15m, df_1h, target=cfg['target'])
            signals = np.where(probs >= cfg['thresh'])[0]
            last_exit_idx = -1
            
            for idx in signals:
                if idx <= last_exit_idx: continue
                entry_time = df.index[idx]
                entry_price = df.iloc[idx]['close']
                tp_price = entry_price * (1 + cfg['tp'])
                sl_price = entry_price * (1 - cfg['sl'])
                
                outcome = "OPEN"
                df_verify = df_5m_raw[df_5m_raw['timestamp'] >= entry_time]
                
                for _, row in df_verify.iterrows():
                    if row['high'] >= tp_price: 
                        outcome = "WIN"
                        res_time = row['timestamp']
                        try:
                            last_exit_idx = df.index.get_indexer([res_time], method='ffill')[0]
                        except:
                            last_exit_idx = idx + 1
                        break
                    if row['low'] <= sl_price: 
                        outcome = "LOSS"
                        res_time = row['timestamp']
                        try:
                            last_exit_idx = df.index.get_indexer([res_time], method='ffill')[0]
                        except:
                            last_exit_idx = idx + 1
                        break
                
                if outcome != "OPEN":
                    all_trades.append({
                        'Time': entry_time,
                        'Model': cfg['name'],
                        'Entry': f"${entry_price:,.0f}",
                        'Result': "✅" if outcome == "WIN" else "❌",
                        'PnL': cfg['tp'] if outcome == "WIN" else -cfg['sl']
                    })

        report = pd.DataFrame(all_trades).sort_values('Time')
        if report.empty:
            print("No trades found.")
            return

        print("\n" + "="*80)
        print("📄 30-DAY MASTER TRADE LOG (Consolidated)")
        print("="*80)
        # Show first 10 and last 10 to keep it readable, but the user wants "go go go"
        # I'll output up to 100 rows
        print(report.to_string(index=False))
        
        print("\n" + "="*80)
        print("📊 MONTHLY PERFORMANCE SUMMARY")
        print("="*80)
        summary = report.groupby('Model')['Result'].value_counts().unstack(fill_value=0)
        if '✅' not in summary: summary['✅'] = 0
        if '❌' not in summary: summary['❌'] = 0
        summary['Win Rate'] = (summary['✅'] / (summary['✅'] + summary['❌']) * 100).map('{:.1f}%'.format)
        summary['Total PnL %'] = (report.groupby('Model')['PnL'].sum() * 100).map('{:.1f}%'.format)
        print(summary)

if __name__ == "__main__":
    MonthlyAudit().simulate()
