
import sys
import os
import pandas as pd
import numpy as np
from datetime import datetime

# Add path access
sys.path.append(os.path.abspath('ADAPTIVE_SHIELD_V1_PRODUCTION'))
sys.path.append(os.path.abspath('ADAPTIVE_SHIELD_V1_PRODUCTION/utils'))

from quant_engine import TradingEngine, add_all_indicators
from utils.trend_filter import get_market_regime, should_trade, get_regime_info

def check_now():
    print("🔍 DIAGNOSING LIVE MARKET REGIME & FILTERS...")
    print("="*60)
    
    engine = TradingEngine()
    
    print("\n📥 Fetching 1H data for Trend Analysis...")
    df_1h = engine.fetch_data('1h', 200)
    
    if df_1h is None or len(df_1h) < 50:
        print("❌ Failed to fetch enough 1H data.")
        return

    # Calculate Regime
    print("📊 Calculating Market Regime...")
    regime_info = get_regime_info(df_1h)
    market_regime = regime_info['regime']
    trend_strength = regime_info['strength']
    
    print("\n" + "="*60)
    print(f"🌊 MARKET REGIME: {market_regime}")
    print(f"   Strength: {trend_strength:.1f}%")
    print(f"   EMA20:    ${regime_info['ema_20']:,.2f}")
    print(f"   EMA50:    ${regime_info['ema_50']:,.2f}")
    print(f"   Price:    ${df_1h.iloc[-1]['close']:,.2f}")
    print("="*60)
    
    # Check Permissions
    can_long, long_reason = should_trade('LONG', market_regime)
    can_short, short_reason = should_trade('SHORT', market_regime)
    
    print("\n🛡️  TREND FILTER PERMISSIONS:")
    print(f"   🟢 LONG Trades:  {'✅ ALLOWED' if can_long else '❌ BLOCKED'} ({long_reason})")
    print(f"   🔴 SHORT Trades: {'✅ ALLOWED' if can_short else '❌ BLOCKED'} ({short_reason})")
    
    if not can_long and not can_short:
        print("\n🔒 CONCLUSION: MARKET IS LOCKED. NO TRADES ALLOWED.")
    elif not can_long:
         print("\n🔒 CONCLUSION: LONGS ARE BLOCKED. (Explains missing buy signals)")
    elif not can_short:
         print("\n🔒 CONCLUSION: SHORTS ARE BLOCKED.")
    else:
        print("\n🔓 CONCLUSION: Filters are OPEN. The issue is low confidence scores.")

    # Also run the confidence check again to be sure
    print("\n" + "-"*60)
    print("🧠 Checking Model Confidence right now...")
    try:
        signal, confidence = engine.check_mtf_scalper()
        print(f"   Current Confidence: {confidence:.2%}")
        if signal:
            direction = signal['direction']
            print(f"   Signal Generated: {direction}")
            # Check interaction
            allowed, reason = should_trade(direction, market_regime)
            if not allowed:
                print(f"   🛑 BUT BLOCKED BY TREND FILTER! ({reason})")
            else:
                print(f"   ✅ AND ALLOWED BY FILTER!")
        else:
            print("   (No Signal generated by model)")
            
    except Exception as e:
        print(f"   Error checking model: {e}")

if __name__ == "__main__":
    check_now()
