steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--no-cache', '-t', 'gcr.io/$PROJECT_ID/quant-engine', '-f', 'Dockerfile.quant', '.']
images:
  - 'gcr.io/$PROJECT_ID/quant-engine'
